theme: jekyll-theme-minimal
title: PsCoinMarketCap
description: PowerShell module for CoinMarketCap API v1 - Cryptocurrency data, monitoring, and analysis tools
logo: PsCoinMarketCap_Logo.png
show_downloads: true
include:
  - docs
  - README.md
  - CHANGELOG.md
  - LICENSE
exclude:
  - Source/
  - Tests/
  - Build/
  - Output/
